
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - wadlewebapp.k8s.wadle.io
  resources:
  - wadlek8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wadlewebapp.k8s.wadle.io
  resources:
  - wadlek8s/finalizers
  verbs:
  - update
- apiGroups:
  - wadlewebapp.k8s.wadle.io
  resources:
  - wadlek8s/status
  verbs:
  - get
  - patch
  - update
