# permissions for end users to edit wadlek8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wadlek8s-editor-role
rules:
- apiGroups:
  - wadlewebapp.k8s.wadle.io
  resources:
  - wadlek8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wadlewebapp.k8s.wadle.io
  resources:
  - wadlek8s/status
  verbs:
  - get
